### ISSUE TITLE
DT BYG requires DT+ 

### ISSUE THREAD

**Issue by MagmaSlime123** [supermassimo/DynamicTrees-BYG#12]
**Describe the bug**
Title. Other mods and their addons may also have this issue, but I don't know.

**To Reproduce**
Install BYG, BOP, and DT with the respective addons.

**Screenshots**

![2022-10-25_18 29 54](https://user-images.githubusercontent.com/51277766/197906661-f10d9246-dc1c-4908-b1ea-bbd3879f6018.png)

An error is also posted in the latest.log as well:
https://pastebin.com/JkyjxkXj

**Rendering Glitches**
Are you using OptiFine (or any equivalent mods that mess with rendering)?
No.

**Additional context**
I have no clue where to post this issue, since both DT BOP/BYG are causing issues.

**Mods List**
What version of Forge are you running? 36.2.39, aka 1.16.5.

![image](https://user-images.githubusercontent.com/51277766/197906489-6787a5a5-af16-40b3-866a-bde3859d2953.png)

**Comment by supermassimo** [comment]
Fixed in [1.0.3](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-byg/files/4452467)
