### ISSUE TITLE
Potentially Dangerous Alternative prefix

### ISSUE THREAD

**Issue by Exophobias** [supermassimo/DynamicTrees-BYG#13]
I am seeing this on every startup, and I was wondering if it is possible to disable the alternative prefix to prevent console spam. 
Thanks

![image](https://user-images.githubusercontent.com/26949488/204160234-e8230d5f-5164-4a86-b206-99dd3bcabb2d.png)

**Comment by supermassimo** [comment]
Those issues are cause by some other mod that messes with the registration, not DTBYG
