### ISSUE TITLE
Missing Texture for Holly Berries

### ISSUE THREAD

**Issue by TristanPeloquin** [supermassimo/DynamicTrees-BYG#2]
Tested without any extra mods, textures still appeared missing. Doesn't seem to be any texture in the files either.
![2022-01-27_20 18 57](https://user-images.githubusercontent.com/98565896/151470342-ac4e4e7b-f780-4ef8-a4c4-5cf758846ca3.png)
![2022-01-27_20 19 13](https://user-images.githubusercontent.com/98565896/151470355-44953cd8-0261-478a-86e2-76fc2f4a5183.png)

**Comment by supermassimo** [comment]
Yes this is known, baobab fruits are missing as well. Remember the addon it was released as a beta, they will be added in the next version.

**Comment by supermassimo** [comment]
Fruit models added in beta 4
