### ISSUE TITLE
palm tree textures are bugged

### ISSUE THREAD

**Issue by TheSexyYeti** [supermassimo/DynamicTrees-BYG#23]
Hay the textures on your palm trees for 1.18.2 are bugged out. Is there any way you can fix that?.

![bug](https://github.com/user-attachments/assets/9de81f5b-5982-49a0-8e4a-28ba2af68efe)

**Comment by supermassimo** [comment]
Unfortunately that's an effect of having graphics set to FAST. All leaves become opaque with that setting. Please set it to FANCY to get better visuals
