### ISSUE TITLE
non-dynamic palms still generating

### ISSUE THREAD

**Issue by swedneck** [supermassimo/DynamicTrees-BYG#5]

**Comment by Whiskey-Sunshine** [comment]
To give further explanation and a visual, as I've run into this issue as well, DTBYG is still generating non-dynamic palms alongside the dynamic versions.
Forge version 36.2.34
DT 1.16.5-0.10.0-Beta33
DTBYG 1.16.5-1.0.0
BYG 1.3.5
Tested it a few times with different world generation types, currently doing this with every world type I've tried. Minecraft, quark, BYG, and terraforged world types all do it, and it happens as standalone mods.

![2022-05-20_02 11 17](https://user-images.githubusercontent.com/30344784/169464350-8ccfd068-2c91-4137-bff2-84d15cc19093.png) - an example on a BYG rainbow beach, both dynamic and normal visible, naturally generated

**Comment by ghost** [comment]
I have this issue as well

**Comment by ghost** [comment]
Does anyone have a workaround for this? I'm using Open Terrain Generator and I still can't remove these ugly trees

**Comment by supermassimo** [comment]
Fixed in [1.0.3](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-byg/files/4452467)
